### PR TITLE
Making the HTML valide

### PR DESCRIPTION
**Pull request by MarauderXtreme**
I've seen that you use image instead of img for 2 of your pictures in the site. I corrected it and included an alt attribute.

### CODE REVIEW

**Comment by JustusAdam** [comment]
Oh good. I had no idea that was incorrect.

I slightly dislike that merge commit but I'll merge it regardless.

As for the `alt` text for the page logo, wouldn't it be better to say "Page logo" or just "Logo" instead of  "Justus Science Logo"?

**Comment by MarauderXtreme** [comment]
I don't know why I had to merge but git told me it was neccessary. I'm too not satisfied with it.

Well the `alt` attribute get's displayed if the images can't be loaded. You can now decide what is better to read in the header. Page Logo or Justus Science Logo.

**Comment by JustusAdam** [comment]
I know. I would have though "Page logo" is better.

**Comment by MarauderXtreme** [comment]
I don't care. You can change it to what you like. Only include it.

**Pull request merged**
